### ISSUE TITLE
[chat] 특수문자 오류

### ISSUE THREAD

**Issue by S00zzang** [1-Stone-3-Birds/SB_Works#13]
![image](https://github.com/user-attachments/assets/39da37b2-6bcf-4c7a-b0af-382e7e7f3827)
특수문자 안 뜨게 해주세용 ㅜ

**Comment by Mingk42** [comment]
- re 패키지 이용하여 문자, 공백 및 지정된 특수문자 외에 출력되지 않도록 조치하였습니다.
- 가능하다면 추후 지정되지 않은 정상적인 특수문자도 출력가능하도록 조치 필요
