### ISSUE TITLE
airflow 어떻게 kafka랑 연동할건지 아이디어좀 공유 ㄱㄱ

### ISSUE THREAD

**Issue by GITSangWoo** [1-Stone-3-Birds/SB_Works#15]
kafka 컨슘에 올라간 채팅 로그데이터 저장한거 어떻게 에어플로우로 처리할껀가요

**Comment by S00zzang** [comment]
제 영역 밖이네요..

**Comment by Mingk42** [comment]
1. log file 읽어서
2. dataframe으로 변환
3. parquet으로 변환

과정으로 처리할 예정입니다.
