### ISSUE TITLE
영화봇 어떻게 구현 의견

### ISSUE THREAD

**Issue by hun0219** [1-Stone-3-Birds/SB_Works#18]
영화봇 구현 
1. 영화진흥위원회에서 API로 받아와서 쓸껀지
2. 기존에 있는 데이터로 쓸껀지
3. 기존 데이터의 범위는??
4. json 형태로 쓸껀지 parquet파일로  쓸껀지?
5. 출력은 어떤식으로?
6. 데이터 칼럼은 뭐뭐 활용할껀지?

**Comment by hun0219** [comment]
기존에 있는 데이터 사용 확정

**Comment by S00zzang** [comment]
기존 데이터가 저는 없어서 api가 되면 그렇게 하고 싶은뎅........ 시간이 오래 걸릴 것 같으면 이미 있는 파일로 하는 것도 괜찮은 것 같아요

**Comment by S00zzang** [comment]
데이터 범위는 년도별 지정보다 필요 컬럼 빼고 다 지워서 전체는 어려울깝쇼...

**Comment by Mingk42** [comment]
1. API로 받는 경우 호출 횟수 제한이 있고, 요청을 받아오는 시간이 소모되어 가능하다면 파일로 저장해두고 불러오면 좋을 것 같습니다.
2. 1과 동일
3. 최대한 많이
4. parquet가 좋지 않을까요
5,6. 새로운 이슈로

**Comment by Mingk42** [comment]
영화 데이터 출력은 어떤식으로 할지

**Comment by Mingk42** [comment]
데이터 칼럼은 뭐뭐 활용할건지

**Comment by hun0219** [comment]
> 데이터 범위는 년도별 지정보다 필요 컬럼 빼고 다 지워서 전체는 어려울깝쇼...

좋은의견이네요
