### ISSUE TITLE
영화 데이터 출력은 어떤식으로 할지

### ISSUE THREAD

**Issue by Mingk42** [1-Stone-3-Birds/SB_Works#19]
영화 데이터 출력은 어떤식으로 할지

_Originally posted by @Mingk42 in https://github.com/1-Stone-3-Birds/SB_Works/issues/18#issuecomment-2314764463_

**Comment by hun0219** [comment]
영화 제목을 기준으로 감독, 영화발행일, 국내/해외 영화 데이터를 출력으로 활용 합시다

"영화"는 "20241212"에 "한국"에서 발행된 "감독"의 영화 입니다. 이런식으로

**Comment by Mingk42** [comment]
좋은 것 같습니다
