### ISSUE TITLE
데이터 칼럼은 뭐뭐 활용할건지

### ISSUE THREAD

**Issue by Mingk42** [1-Stone-3-Birds/SB_Works#20]
데이터 칼럼은 뭐뭐 활용할건지

_Originally posted by @Mingk42 in https://github.com/1-Stone-3-Birds/SB_Works/issues/18#issuecomment-2314765580_

**Comment by hun0219** [comment]
https://github.com/1-Stone-3-Birds/SB_Works/issues/19#issuecomment-2314772262
여기 형식으로 하면 될듯

**Comment by Mingk42** [comment]
좋습니다
